baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Sysmic Robotics'
theme = 'ananke'

[params]
description = "Sysmic es una organización estudiantil enfocada a la investigación y desarrollo de robots autónomos capaces de jugar fútbol en la competencia mundial RoboCup."
featured_image = '/cover.jpg'

[params.ananke.social]
[params.ananke.social.follow]
networks = ["instagram", "linkedin", "tiktok", "youtube"]

[params.ananke.social.instagram]
username = "sysmic.robotics"

[params.ananke.social.linkedin]
username = "sysmic-robotics"

[params.ananke.social.youtube]
username = "sysmic.robotics"

[params.ananke.social.tiktok]
username = "sysmicrobotics"

[params.ananke.social.networks.instagram]
label = "Instagram"
icon = "instagram"
profile = "https://instagram.com/%s"

[params.ananke.social.networks.linkedin]
label = "LinkedIn"
icon = "linkedin"
profile = "https://www.linkedin.com/company/%s"

[params.ananke.social.networks.youtube]
label = "YouTube"
icon = "youtube"
profile = "https://www.youtube.com/@%s"

[params.ananke.social.networks.tiktok]
label = "TikTok"
icon = "tiktok"
profile = "https://www.tiktok.com/@%s"

[[menu.main]]
name = "Posts"
url = "/post/"
weight = 1

[[menu.main]]
name = "Sobre Nosotros"
url = "/sobre-nosotros/"
weight = 2

[[menu.main]]
name = "Contacto"
url = "/contacto/"
weight = 3

[markup.goldmark.renderer]
unsafe = true